#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "22i $str" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > error-404-page.html
str="\\\terror_page 404 /error-404-page.html"
sudo sed -i "22i $str" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
