#!/usr/bin/env bash
# installs a web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "63i \\\tadd_header X-Served-By $(hostname);" /etc/nginx/nginx.conf
sudo service nginx restart 
